name: Java Release

on:
  push:
    branches: [ release ]
    paths:
      - '.github/workflows/java.yml'
      - '.github/workflows/java-release.yml'
      - 'packages/java/**/*'
      - 'scripts/**/*'
      - 'pom.xml'

jobs:
  testing:
    name: Test & Analysis
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Checkout Project Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up OpenJDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Configure Git user
        run: |
          git config user.email "vaadin-bot@users.noreply.github.com"
          git config user.name "vaadin-bot"
      - name: Publish JAR
        run: ./mvnw -B release:prepare -DreleaseVersion=0.0.20 -Dtag=0.0.20 -DdevelopmentVersion=1.0-SNAPSHOT 
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_RELEASE_TOKEN }}
