name: Java Release

on:
  push:
    branches: [ release ]
    paths:
      - '.github/workflows/java.yml'
      - '.github/workflows/java-release.yml'
      - 'packages/java/**/*'
      - 'scripts/**/*'
      - 'pom.xml'

env:
  RELEASE_VERSION: 0.0.20
  NEXT_VERSION: 1.0-SNAPSHOT

jobs:
  releasing:
    name: Release
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Checkout Project Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
      - name: Configure Git user
        run: |
          git config user.email "vaadin-bot@users.noreply.github.com"
          git config user.name "vaadin-bot"
      - name: Publish JAR
        run: mvn -B release:prepare -DreleaseVersion=${RELEASE_VERSION} -Dtag=${RELEASE_VERSION} -DdevelopmentVersion=${NEXT_VERSION}
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_RELEASE_TOKEN }}
