name: Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: Release Version
        required: true
      developmentVersion:
        description: Next Development Version
        required: true

jobs:
  releasing:
    name: Release
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Checkout Project Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Publish JAR
        run: |
          echo "Release Version: ${{github.event.inputs.releaseVersion}}"
          echo "Next Development Version: ${{github.event.inputs.developmentVersion}}"
          mvn -B release:prepare -DreleaseVersion=${{github.event.inputs.releaseVersion}} -Dtag=${{github.event.inputs.releaseVersion}} -DdevelopmentVersion=${{github.event.inputs.developmentVersion}}
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_RELEASE_TOKEN }}
