name: Java Release

env:
  PROFILE: prerelease

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: Release Version
        required: true
      developmentVersion:
        description: Next Development Version
        required: true

jobs:
  releasing:
    name: Release
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Set Release Profile
        run: |
          echo "$PROFILE"
          PROFILE = $([[ ${{ github.event.inputs.releaseVersion }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] && echo "maven-central" || echo "prerelease")
          echo "$PROFILE"

      - name: Checkout Project Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
